# Generated by Django 3.2.3 on 2021-10-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psixolog', '0003_auto_20211017_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologist',
            name='resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologist',
            name='specialist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
