# Generated by Django 3.2.3 on 2021-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psixolog', '0004_auto_20211019_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='info',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
