# Generated by Django 3.2.3 on 2021-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psixolog', '0007_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
