# Generated by Django 3.2.3 on 2021-11-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': "Ro'yxat", 'verbose_name_plural': "Savollar ro'yxati"},
        ),
    ]
